### ISSUE TITLE
Correction needed in documentation (Installation Procedure)

### ISSUE THREAD

**Issue by rehanalis** [RittmanMead/insights#1]
Correction is required in Installation procedure guide (file installation.html under docs folder)

>  1. Unzip the source code archive and rename the output directory to **web-api**. 

This should be changed to
1. Unzip the source code archive and rename the output directory to **insights**.  

Further snapshot given in step 9, should also reflect the same.

**Comment by rmoff** [comment]
@rehanalis we're open to pull requests if you'd like to submit one :) 
/cc @mineshpatel1

**Comment by mineshpatel1** [comment]
Fixed in commit: d12b0ccb28798124737665e1906d042c3e8454ba
