### ISSUE TITLE
Error exploring catalogue

### ISSUE THREAD

**Issue by spkoes** [RittmanMead/insights#2]
I get a null exception at:
// Current user application roles
			var userRoles = obiee.BIVariables.Session.filter(function(v) {
				return v.Name == 'ROLES';
			})[0].Value;

I can log in and get data from subjets areas, but I can't save or explore catalogue.
It's about instanceconfig.xml change?¿

**Comment by mineshpatel1** [comment]
This is not to do with the `instanceconfig.xml` change, rather I think it is because the session variables haven't been populated. What version of OBIEE are you running?

**Comment by spkoes** [comment]
11.1.1.7
We are planning the migration to 12c but now we are in that version

**Comment by mineshpatel1** [comment]
I suspected as much. As the documentation explains, Insights is unsupported on 11.1.1.7 for two major reasons:

* Web Services on 11.1.1.7 don't support decimals
* Session and Repository variables aren't retrievable through logical SQL (or at least not in the same way)

The latter problem is why you're receiving your specific error, but there are more severe problems on 11.1.1.7 that you've not picked up yet.

All of these things can be worked around, but they're not perfectly comprehensive so I didn't want to commit the workarounds to the main branches. We can (and have in the past) implement the workarounds in such a manner that they will allow interoperability when you upgrade to 12c.

Feel free to [contact us](https://www.rittmanmead.com/contact/) or email directly to [info@rittmanmead.com](mailto:info@rittmanmead.com) if you want to pursue this further.
