### ISSUE TITLE
Need suggestions

### ISSUE THREAD

**Issue by robs15** [RittmanMead/insights#4]
Hi,
    First of all, thanks for this wonderful contribution. I know this is not the right place to ask, but couldn't find a better place.
    I would like to use this for our enterprise application which is on a MS SQL Server db. Was going through the code base, still need time to figure out where to start. 
    Was trying to bypass certain code blocks to atleast run the app, somehow managed to go till the viz builder section, but, obviously, it shows nothing, since, I believe, it needs some data structure to load and display.
    Can you please give me some pointers as to which js modules should I concentrate on to do the needful? Also, is there some sort of stub data which can be fed to the app for now to atleast enable it to display correctly.
    I might be sounding naive, but, for now, am clueless and need to reach to some conclusion. I also tried installing and configuring Oracle Weblogic Server, but nothing's shown up on the screen. I believe, it's the missing data/db.

Thanks,
Robi.

**Comment by mineshpatel1** [comment]
Unfortunately Insights is very tightly coupled to OBIEE. If you are not using OBIEE, there would need to be quite a dramatic change to the code base, which would be tantamount to making the BI tool from scratch.

You would need to introduce a server layer (at the moment OBIEE is used as the server layer), which would be able to perform certain actions that are impossible in the web browser like storing metadata and executing queries. Then you would need to replace the subject area, table and dynamic SQL generation code with code that's relevant to your system, as well as providing the application with similarly translated metadata about the columns.

Sorry to say, but you won't be able to get Insights working without OBIEE, or a lot of work.
