### ISSUE TITLE
Relationship between tables

### ISSUE THREAD

**Issue by robs15** [RittmanMead/insights#5]
From what I could understand, subject areas are similar to databases from a SQL server point of view and you list the tables on the left pane. How does insights take into account the relationship? While building interactivity between 2 visualizations or building filters, etc., does the app take care of relationships to avoid improper queries?

**Comment by mineshpatel1** [comment]
Insights is only a front end application that sits on top of OBIEE, a BI tool that is designed to have a metadata layer that takes into account these relationships. The server layer of OBIEE is responsible for generating physical queries, based on this metadata file. Insights does not seek to replicate or replace any of that functionality.

If you wanted to use Insights without OBIEE you would have to write an equivalent metadata/processing layer that handles these relationships. The scope of that task is potentially very wide, given all of the things that OBIEE does regarding security and physical query generation. However it is feasible to me to build an ad-hoc system whereby each report has a set of queries and transformations defined, resulting in a single "subject area" for each report. However then the onus is on the user to build correct queries and transformations.
